#!/bin/bash

# QA Agent - Claude Code Integration
# This script demonstrates how to invoke Claude Code to fix test failures

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🤖 QA Agent - Claude Code Integration${NC}"
echo -e "${BLUE}======================================${NC}"
echo ""

# Check if Claude Code is available
if ! command -v claude &> /dev/null; then
    echo -e "${YELLOW}⚠ Claude Code CLI not found${NC}"
    echo ""
    echo "Please install Claude Code CLI to use this script."
    echo "Visit: https://claude.ai/code"
    echo ""
    echo "Alternative: Use the QA agent skill manually:"
    echo "  1. Load the qa-agent skill in Claude Code"
    echo "  2. Provide the test failure logs"
    echo "  3. Request fixes following TDD principles"
    exit 1
fi

# Check for prompt file
PROMPT_FILE="$PROJECT_ROOT/qa-agent-prompt.txt"
if [ ! -f "$PROMPT_FILE" ]; then
    echo -e "${YELLOW}⚠ No prompt file found${NC}"
    echo ""
    echo "Run ./scripts/qa-agent.sh first to generate the prompt file."
    exit 1
fi

echo -e "${GREEN}✓ Found QA agent prompt file${NC}"
echo ""

# Show prompt preview
echo -e "${YELLOW}Prompt Preview:${NC}"
head -n 20 "$PROMPT_FILE"
echo "..."
echo ""

# Ask for confirmation
read -p "Start Claude Code to fix these issues? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Cancelled."
    exit 0
fi

# Create git branch for fixes
COMMIT_SHA=$(git rev-parse --short HEAD)
BRANCH_NAME="qa-agent/fix-$COMMIT_SHA"

echo -e "${BLUE}Creating branch: $BRANCH_NAME${NC}"
git checkout -b "$BRANCH_NAME"

echo ""
echo -e "${GREEN}✓ Branch created${NC}"
echo ""

# Invoke Claude Code
echo -e "${BLUE}Invoking Claude Code...${NC}"
echo ""

# Option 1: Use Claude Code CLI with chat mode
# This allows interactive fixing with the agent
echo "Starting Claude Code in chat mode..."
echo "The QA agent prompt has been loaded as context."
echo ""
echo "Instructions for Claude Code:"
echo "1. Analyze the test failures in the prompt"
echo "2. Fix each failing test following TDD principles"
echo "3. Generate missing tests for new features"
echo "4. Verify all tests pass"
echo "5. Commit the changes"
echo ""

# Start Claude Code with the project context
cd "$PROJECT_ROOT"

# Create a temporary file with initial instructions
INIT_MESSAGE=$(cat <<EOF
You are a QA autonomous agent. I need you to:

1. Review the test failures and missing tests in qa-agent-prompt.txt
2. Fix all failing tests using TDD principles:
   - Understand the root cause first
   - Fix tests or implementation as appropriate
   - Never just skip tests or increase timeouts without understanding why
3. Generate tests for any new features that lack coverage
4. Follow existing test patterns in the codebase
5. Run tests after each fix to verify
6. Commit changes with clear messages

After you're done:
- Create a commit with message: "test: fix failing tests and add missing coverage (QA agent)"
- Summary what you fixed
- Let me know if you need any clarification

Ready to start?
EOF
)

# Save initial message
echo "$INIT_MESSAGE" > "$PROJECT_ROOT/qa-agent-initial-message.txt"

echo "Initial instructions:"
echo "$INIT_MESSAGE"
echo ""

# Option A: Interactive mode (recommended)
echo -e "${YELLOW}Starting interactive Claude Code session...${NC}"
echo ""
claude chat --project="$PROJECT_ROOT"

# After Claude Code session ends
echo ""
echo -e "${GREEN}✓ Claude Code session completed${NC}"
echo ""

# Check if changes were made
if [[ -n $(git status -s) ]]; then
    echo -e "${GREEN}✓ Changes detected${NC}"
    echo ""
    git status
    echo ""

    read -p "Push branch and create PR? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${BLUE}Pushing branch...${NC}"
        git push -u origin "$BRANCH_NAME"

        echo ""
        echo -e "${BLUE}Creating PR...${NC}"

        # Create PR using gh CLI
        gh pr create \
            --title "🤖 QA Agent: Fix tests for $COMMIT_SHA" \
            --body "$(cat <<EOF
## 🤖 QA Agent Auto-Fix

This PR was automatically generated by the QA agent to fix test failures and add missing test coverage.

**Original Commit:** \`$COMMIT_SHA\`

### Changes Made

<!-- Claude Code will have listed changes in commit message -->

### Test Results

Run the CI pipeline to verify all tests now pass.

### Review Checklist

- [ ] Review test fixes for correctness
- [ ] Verify new tests follow existing patterns
- [ ] Check that root causes were addressed (not just symptoms)
- [ ] Ensure no working code was broken

---

*Auto-generated by QA Agent*
*Manual review required before merging*
EOF
)" \
            --label "qa-agent" \
            --label "automated"

        echo ""
        echo -e "${GREEN}✓ PR created successfully${NC}"

        # Get PR URL
        PR_URL=$(gh pr view --json url -q .url)
        echo ""
        echo "PR URL: $PR_URL"
    else
        echo "Changes not pushed. Branch created locally: $BRANCH_NAME"
    fi
else
    echo -e "${YELLOW}⚠ No changes detected${NC}"
    echo ""
    echo "Claude Code may not have made any changes, or the changes may already be committed."

    # Clean up branch
    git checkout main
    git branch -D "$BRANCH_NAME"
fi

echo ""
echo -e "${BLUE}QA Agent session complete${NC}"
