// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Training.Infrastructure.Persistence;

#nullable disable

namespace Training.Infrastructure.Migrations
{
    [DbContext(typeof(TrainingDbContext))]
    partial class TrainingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Training.Domain.Entities.CoachGymnastRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GymnastId")
                        .HasColumnType("uuid")
                        .HasColumnName("gymnast_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_coach_gymnast_relationships_coach_id");

                    b.HasIndex("GymnastId")
                        .HasDatabaseName("ix_coach_gymnast_relationships_gymnast_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_coach_gymnast_relationships_tenant_id");

                    b.HasIndex("TenantId", "CoachId", "GymnastId")
                        .IsUnique()
                        .HasDatabaseName("ix_coach_gymnast_relationships_unique");

                    b.ToTable("coach_gymnast_relationships", (string)null);
                });

            modelBuilder.Entity("Training.Domain.Entities.ProgrammeBuilderSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ConversationHistoryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("conversation_history_json");

                    b.Property<Guid>("GymnastId")
                        .HasColumnType("uuid")
                        .HasColumnName("gymnast_id");

                    b.Property<string>("InitialGoals")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("initial_goals");

                    b.Property<string>("RagScopeConfig")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rag_scope_config");

                    b.Property<Guid?>("ResultingProgrammeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resulting_programme_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_programme_builder_sessions_coach_id");

                    b.HasIndex("GymnastId")
                        .HasDatabaseName("ix_programme_builder_sessions_gymnast_id");

                    b.HasIndex("ResultingProgrammeId")
                        .HasDatabaseName("ix_programme_builder_sessions_resulting_programme_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_programme_builder_sessions_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_programme_builder_sessions_tenant_id");

                    b.ToTable("programme_builder_sessions", (string)null);
                });

            modelBuilder.Entity("Training.Domain.Entities.ProgrammeMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoachId")
                        .HasColumnType("uuid")
                        .HasColumnName("coach_id");

                    b.Property<string>("CouchDbDocId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("couchdb_doc_id");

                    b.Property<string>("CouchDbRev")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("couchdb_rev");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector")
                        .HasColumnName("embedding_vector");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid>("GymnastId")
                        .HasColumnType("uuid")
                        .HasColumnName("gymnast_id");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .HasDatabaseName("ix_programme_metadata_coach_id");

                    b.HasIndex("CouchDbDocId")
                        .IsUnique()
                        .HasDatabaseName("ix_programme_metadata_couchdb_doc_id");

                    b.HasIndex("GymnastId")
                        .HasDatabaseName("ix_programme_metadata_gymnast_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_programme_metadata_tenant_id");

                    b.HasIndex("TenantId", "GymnastId")
                        .IsUnique()
                        .HasDatabaseName("ix_programme_metadata_active_per_gymnast")
                        .HasFilter("status = 1");

                    b.HasIndex("TenantId", "GymnastId", "Status")
                        .HasDatabaseName("ix_programme_metadata_tenant_gymnast_status");

                    b.ToTable("programme_metadata", (string)null);
                });

            modelBuilder.Entity("Training.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_tenant_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("EffectivenessRating")
                        .HasColumnType("integer")
                        .HasColumnName("effectiveness_rating");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector")
                        .HasColumnName("embedding_vector");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByTenantId")
                        .HasDatabaseName("ix_skills_created_by_tenant_id");

                    b.HasIndex("EffectivenessRating")
                        .HasDatabaseName("ix_skills_effectiveness_rating");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_skills_title");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_skills_usage_count");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Training.Domain.Entities.SkillSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Section")
                        .HasColumnType("integer")
                        .HasColumnName("section");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("Section")
                        .HasDatabaseName("ix_skill_sections_section");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_skill_sections_skill_id");

                    b.HasIndex("SkillId", "Section")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_sections_skill_section_unique");

                    b.ToTable("skill_sections", (string)null);
                });

            modelBuilder.Entity("Training.Domain.Entities.SkillSection", b =>
                {
                    b.HasOne("Training.Domain.Entities.Skill", "Skill")
                        .WithMany("Sections")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Training.Domain.Entities.Skill", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
